### ISSUE TITLE
CI: Nightly run

### ISSUE THREAD

**Issue by yihuaf** [kontainapp/km#485]
The current design of runenv image requires a new k8s cluster to test everytime. This is prohibitively long for normal dev cycle. There are also km and node tests that take much longer time to run today. The decision is to have a nightly run of the master branch.

- [x] Launch CI with a nightly trigger #493 

- [x] Start k8s cluster from the CI VM launched #505 

- [x] Run unit test with the nightly build #521

- [x] turn on node and other long running test #527

- [x] runenv validation #530
