### ISSUE TITLE
Merge kkm module into km and CI

### ISSUE THREAD

**Issue by yihuaf** [kontainapp/km#558]
- [x] - add kkm repo as a submodule to KM (suggestion: in ./kkm folder) #559 
- [x] - add / PR / merge changes to KM and tests so they work with kkm  #569
- [x] - Add kkm build and install to CI. #580 
- [x] - Run tests using kkm #581
